### ISSUE TITLE
Does not work on Managed Disks VM

### ISSUE THREAD

**Issue by lukemurraynz** [bobalob/ARM-HybridUse#1]
Due to the nature of the script - pointing towards a VHD. This script:
Deallocates and deletes the VM, however, cannot recreate it. on Virtual Machines using managed disks. 

I have tested this on x1 VM with standard disks (unmanaged) and it has worked perfectly.

**Comment by bobalob** [comment]
**Added Managed Disk support!** 

Tested with Managed & Unmanaged with data disks, also B-Series

Thanks for your feedback.
